### ISSUE TITLE
error gr::sync_block on TSI (Ubuntu 22.04 + HackRF)

### ISSUE THREAD

**Issue by gcarmix** [ainfosec/FISSURE#30]
I'm trying to use FISSURE for the first time, I installed it on Ubuntu 22.04 and followed instructions, all seemed correctly installed, however when I tried to use TSI together with my hackrf, it won't show anything and output this error on the shell:  

TSI: Starting TSI Detector...

Exception in thread Thread-1 (runWidebandThread):

Traceback (most recent call last):

  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner

    self.run()

  File "/usr/lib/python3.10/threading.py", line 953, in run

    self._target(*self._args, **self._kwargs)

  File "/home/xxx/FISSURE/tsi_component.py", line 385, in runWidebandThread

    loadedmod, class_name = self.overwriteFlowGraphVariables(flow_graph_filename, variable_names, variable_values)

File "/home/xxx/FISSURE/tsi_component.py", line 198, in overwriteFlowGraphVariables

    loadedmod = __import__(flow_graph_filename)  # Don't need to reload() because the original never changes

  File "/home/xxx/FISSURE/Flow Graph Library/TSI Flow Graphs/wideband_hackrf.py", line 23, in <module>

    import gnuradio.ainfosec as ainfosec

  File "/usr/local/lib/python3.10/dist-packages/gnuradio/ainfosec/__init__.py", line 18, in <module>

    from .ainfosec_python import *

ImportError: generic_type: type "wideband_detector1" referenced unknown base type "gr::sync_block"

Do you have any hints?

**Comment by cpoore1** [comment]
Seems like a GNU Radio problem. Try some of these:
- `python3 -c "import gnuradio.ainfosec as ainfosec"` to see if there are any errors with the gr-ainfosec installation
- check the GNU Radio version, I'm expecting some type of 3.10 like 3.10.5.0, it prints the version after running `gnuradio-companion`
- check the FISSURE branch to see if it is in Python3_maint-3.10 branch, `cd FISSURE`, `git branch`
- Open "/FISSURE/Flow Graph Library/TSI Flow Graphs/wideband/wideband_hackrf.grc", check for errors, execute the flow graph and see if it stays open with the HackRF connected
- Run `hackrf_sweep` to see if there is output
- Try another HackRF flow graph, set HackRF in the FISSURE hardware buttons, go to IQ Data>Inspection>waterfall_hackrf.py, see a waterfall GUI on start (looks like instantaneous_frequency_hackrf.py needed to be regenerated)

**Comment by cpoore1** [comment]
Thanks for reporting this. This error came from the older TSI implementation and `gnuradio.ainfosec` out-of-tree module failing to load its `wideband_detector1` block correctly against the installed GNU Radio environment.

The TSI detector architecture, flow graphs, installer dependencies, and GNU Radio support have been substantially overhauled since this issue was opened, and the referenced `tsi_component.py` and `wideband_hackrf.py` paths no longer represent the current implementation.

I’m going to close this against the older implementation. If HackRF detection fails with the current Ubuntu 22.04 installer and current detector workflow, please open a new issue with the selected installation mode, current commit, GNU Radio version, and complete terminal output.
